### ISSUE TITLE
not getting proper result while doing ocr using java application in linux machine but "tesseract photo.jpg stdout" command giving proper results but getting Error in boxClipToRectangle: box outside rectangle, Error in pixScanForForeground: invalid box we need to integrate tessract in java application and will be tested in linux machine.

### ISSUE THREAD

**Issue by karna123** [conda-forge/tesseract-feedstock#22]
Issue:

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by CurtLH** [comment]
Hi @karna123 -- thank for highlight the issue you are experiencing.  I suggest you open an issue with the [source code repository respoitory](https://github.com/tesseract-ocr/tesseract/).  Once they make a fix, we can pick it up as a new version within Conda Forge.
