### ISSUE TITLE
Tesseract 4 

### ISSUE THREAD

**Issue by makmanalp** [conda-forge/tesseract-feedstock#6]
Hi, would there be any interest in providing packages for tesseract 4 in this feedstock?

The downside is that tesseract 4 is beta/unstable, and I don't know whether it should have its own feedstock (like `tesseract4`), and whether/not that's against conda-forge policy.

There used to be some t4 packages from here: https://anaconda.org/mcs07/tesseract (repo here: https://github.com/mcs07/conda-recipes) but it looks like the author removed the t4 ones.

**Comment by CurtLH** [comment]
Typically beta packages do not go into conda-forge.

Any thoughts from @conda-forge/core?

**Comment by makmanalp** [comment]
@CurtLH That's fair. Another question is that there's probably going to come a time when t4 comes out of beta, but they'll likely be people still wanting to use t3 then because of incompatibilities (e.g. different tessdata files and config options, etc etc). Will that just work as usual, by pinning to the 3.x version?

**Comment by jakirkham** [comment]
In light of this discussion, what would we like to do with PR ( https://github.com/conda-forge/tesseract-feedstock/pull/7 )?
